version: 2

submodules:
  include: all

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  apt_packages:
  - cmake
  jobs:
    post_install:
    - bash docs/generate_api_reference.sh

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true

python:
    install:
    - requirements: docs/requirements.txt
    - method: pip
      path: client/
